export const Quotes = [{ id:1 ,quote: `Muddy water is best cleared by leaving it alone`},
    { id:2 ,quote: `You can’t live at all unless you can live fully now.`},
    { id:3 ,quote: `The most dangerous risk of all: the risk of spending your life not doing what you want on the bet you can buy yourself the freedom to do it later.`},
    { id:4 ,quote: `This is the real secret of life — to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.`},
    { id:5 ,quote: `Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.`},
    { id:6 ,quote: `One is a great deal less anxious if one feels perfectly free to be anxious, and the same may be said of guilt.`},
    { id:7 ,quote: `Never pretend to a love which you do not actually feel, for love is not ours to command.`},
    { id:8 ,quote: `Money is an abstraction. It cannot, of itself, buy any pleasure whatsoever. Because all pleasures involve skill and love.`},
    { id:9 ,quote: `Love is not something that is a sort of rare commodity, everybody has it.`},
    { id:10 ,quote: `Life and love generate effort, but effort will not generate them. Faith in life, in other people, and in oneself, is the attitude of allowing the spontaneous to be spontaneous, in its own way and in its own time.`},
    { id:11 ,quote: `People who exude love are apt to give things away. They are in every way like rivers; they stream. And so when they collect possessions and things they like, they are apt to give them to other people. Because, have you ever noticed that when you start giving things away, you keep getting more?`},
    { id:12 ,quote: `Everyone has love, but it can only come out when he is convinced of the impossibility and the frustration of trying to love himself. This conviction will not come through condemnations, through hating oneself, through calling self love bad names in the universe. It comes only in the awareness that one has no self to love.`},
    { id:13 ,quote: `Peace can be made only by those who are peaceful, and love can be shown only by those who love. No work of love will flourish out of guilt, fear, or hollowness of heart, just as no valid plans for the future can be made by those who have no capacity for living now.`},
    { id:14 ,quote: `We seldom realize, for example that our most private thoughts and emotions are not actually our own. For we think in terms of languages and images which we did not invent, but which were given to us by our society.`},
    { id:15 ,quote: `To have faith is to trust yourself.`},
    { id:16 ,quote: `Just as true humor is laughter at oneself, true humanity is knowledge of oneself.`},
    { id:17 ,quote: `Man suffers only because he takes seriously what the Gods made for fun.`},
    { id:18 ,quote: `Trying to define yourself is like trying to bite your own teeth.`},
    { id:19 ,quote: `You are an aperture through which the universe is looking at and exploring itself.`},
    { id:20 ,quote: `A scholar tries to learn something everyday; a student of Buddhism tries to unlearn something daily.`},
    { id:21 ,quote: `The real you is the whole universe.`},
    { id:22 ,quote: `Every intelligent individual wants to know what makes him tick, and yet is at once fascinated and frustrated by the fact that oneself is the most difficult of all things to know.`},
    { id:23 ,quote: `Don’t make a distinction between work and play. Regard everything that you’re doing as play, and don’t regard for one minute that you have to be serious about it.`},
    { id:24 ,quote: `We are living in a culture entirely hypnotized by the illusion of time, in which the so-called present moment is felt as nothing but an infinitesimal hairline between an all-powerfully causative past and an absorbingly important future. We have no present. Our consciousness is almost completely preoccupied with memory and expectation. We do not realize that there never was, is, nor will be any other experience than present experience. And are therefore out of touch with reality. We confuse the world as talked about, described, and measured with the world which actually is. We are sick with a fascination for the useful tools of names and numbers, of symbols, signs, conceptions and ideas.`},
    { id:25 ,quote: `When we attempt to exercise power or control over someone else, we cannot avoid giving that person the very same power or control over us.`},
    { id:26 ,quote: `If you cannot trust yourself, you cannot even trust your mistrust of yourself – so that without this underlying trust in the whole system of nature you are simply paralyzed.`},
    { id:27 ,quote: `No one is more dangerously insane than one who is sane all the time: he is like a steel bridge without flexibility, and the order of his life is rigid and brittle.`},
    { id:28 ,quote: `What we have to discover is that there is no safety, that seeking is painful, and that when we imagine that we have found it, we don’t like it.`},
    { id:29 ,quote: `The only way to make sense out of change is to plunge into it, move with it, and join the dance.`},
    { id:30 ,quote: `Hospitals should be arranged in such a way as to make being sick an interesting experience. One learns a great deal sometimes from being sick.`},
    { id:31 ,quote: `Our pleasures are not material pleasures, but symbols of pleasure – attractively packaged but inferior in content.`},
    { id:32 ,quote: `Normally, we do not so much look at things as overlook them.`},
    { id:33 ,quote: `The art of living… is neither careless drifting on the one hand nor fearful clinging to the past on the other. It consists in being sensitive to each moment, in regarding it as utterly new and unique, in having the mind open and wholly receptive.`},
    { id:34 ,quote: `It’s better to have a short life that is full of what you like doing, than a long life spent in a miserable way.`},
    { id:35 ,quote: `The meaning of life is just to be alive. It is so plain and so obvious and so simple. And yet, everybody rushes around in a great panic as if it were necessary to achieve something beyond themselves.`},
    { id:36 ,quote: `You are a function of what the whole universe is doing in the same way that a wave is a function of what the whole ocean is doing.`},
    { id:37 ,quote: `Tomorrow and plans for tomorrow can have no significance at all unless you are in full contact with the reality of the present, since it is in the present and only in the present that you live. There is no other reality than present reality, so that, even if one were to live for endless ages, to live for the future would be to miss the point everlastingly.`},
    { id:38 ,quote: `If you say that getting the money is the most important thing, you’ll spend your life completely wasting your time. You’ll be doing things you don’t like doing in order to go on living, that is to go on doing thing you don’t like doing, which is stupid.`},
    { id:39 ,quote: `I have realized that the past and future are real illusions, that they exist in the present, which is what there is and all there is.`},
    { id:40 ,quote: `Zen does not confuse spirituality with thinking about God while one is peeling potatoes. Zen spirituality is just to peel the potatoes.`},
    { id:41 ,quote: `We cannot be more sensitive to pleasure without being more sensitive to pain.`},
    { id:42 ,quote: `The more a thing tends to be permanent, the more it tends to be lifeless.`},
    { id:43 ,quote: `If we cling to belief in God, we cannot likewise have faith, since faith is not clinging but letting go.`},
    { id:44 ,quote: `Through our eyes, the universe is perceiving itself. Through our ears, the universe is listening to its harmonies. We are the witnesses through which the universe becomes conscious of its glory, of its magnificence.`},
    { id:45 ,quote: `Things are as they are. Looking out into the universe at night, we make no comparisons between right and wrong stars, nor between well and badly arranged constellations.`},
    { id:46 ,quote: `To have faith is to trust yourself to the water. When you swim you don’t grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.`},
    { id:47 ,quote: `What I am really saying is that you don’t need to do anything, because if you see yourself in the correct way, you are all as much extraordinary phenomenon of nature as trees, clouds, the patterns in running water, the flickering of fire, the arrangement of the stars, and the form of a galaxy. You are all just like that, and there is nothing wrong with you at all.`},
    { id:48 ,quote: `The reason we want to go on and on is because we live in an impoverished present.`},
    { id:49 ,quote: `Try to imagine what it will be like to go to sleep and never wake up… now try to imagine what it was like to wake up having never gone to sleep.`},
    { id:50 ,quote: `Omnipotence is not knowing how everything is done; it’s just doing it.`},
    { id:51 ,quote: `My image of me is not at all your image of me.`},
    { id:52 ,quote: `You don’t look out there for God, something in the sky, you look in you.`},
    { id:53 ,quote: `The reason we have poverty is that we have no imagination. There are a great many people accumulating what they think is vast wealth, but it’s only money… they don’t know how to enjoy it, because they have no imagination.`},
    { id:54 ,quote: `We do not ‘come into’ this world; we come out of it, as leaves from a tree.`},
    { id:55 ,quote: `How is it possible that a being with such sensitive jewels as the eyes, such enchanted musical instruments as the ears, and such fabulous arabesque of nerves as the brain can experience itself anything less than a god.`},
    { id:56 ,quote: `What the devil is the point of surviving, going on living, when it’s a drag? But you see, that’s what people do.`},
    { id:57 ,quote: `Saints need sinners.`},
    { id:58 ,quote: `Philosophy is man’s expression of curiosity about everything and his attempt to make sense of the world primarily through his intellect.`},
    { id:59 ,quote: `The positive cannot exist without the negative.`},
    { id:60 ,quote: `Everything that happens, everything that I have ever done, everything that anybody else have ever done is part of a harmonious design, that there is no error at all.`},
    { id:61 ,quote: `Meditation is the discovery that the point of life is always arrived at in the immediate moment.`},
    { id:62 ,quote: `Your soul is not in your body; your body is in your soul.`},
    { id:63 ,quote: `Life exists only at this very moment, and in this moment it is infinite and eternal, for the present moment is infinitely small; before we can measure it, it has gone, and yet it exists forever….`},
    { id:64 ,quote: `To put is still more plainly: the desire for security and the feeling of insecurity are the same thing. To hold your breath is to lose your breath.`},
    { id:65 ,quote: `For there is never anything but the present, and if one cannot live there, one cannot live anywhere.`},
    { id:66 ,quote: `There will always be suffering. But we must not suffer over the suffering.`},
    { id:67 ,quote: `You’re under no obligation to be the same person you were 5 minutes ago.`},
    { id:68 ,quote: `Like too much alcohol, self-consciousness makes us see ourselves double, and we make the double image for two selves – mental and material, controlling and controlled, reflective and spontaneous. Thus instead of suffering we suffer about suffering, and suffer about suffering about suffering.`},
    { id:69 ,quote: `Really, the fundamental, ultimate mystery — the only thing you need to know to understand the deepest metaphysical secrets — is this: that for every outside there is an inside and for every inside there is an outside, and although they are different, they go together.`},
    { id:70 ,quote: `Don’t hurry anything or worry about the future or worry about what progress you’re making. Just be entirely content to be aware of what is.`},
    { id:71 ,quote: `Zen is a way of liberation, concerned not with discovering what is good or bad or advantageous, but what is.`},
    { id:72 ,quote: `What happens if you know that there is nothing you can do to be better? It’s kind of a relief, isn’t it? You say ‘Well, now what do I do?’ When you are freed from being out to improve yourself, your own nature will begin to take over.`},
    { id:73 ,quote: `To travel is to be alive, but to get somewhere is to be dead, for as our own proverb says, To travel well is better than to arrive.`},
    { id:74 ,quote: `When you know that you have to go with the river, suddenly you acquire—behind everything that you do—the power of the river.`},
    { id:75 ,quote: `Only those who have cultivated the art of living completely in the present have any use for making plans for the future, for when the plans mature they will be able to enjoy the results.`},
    { id:76 ,quote: `Paradoxical as it may seem, the purposeful life has no content, no point. It hurries on and on, and misses everything. Not hurrying, the purposeless life misses nothing, for it is only when there is no goal and no rush that the human senses are fully open to receive the world.`},
    { id:77 ,quote: `Waking up to who you are requires letting go of who you imagine yourself to be.`},
    { id:78 ,quote: `Tomorrow never comes.`},
    { id:79 ,quote: `When a bird sings, it doesn’t sing for the advancement of music.`},
    { id:80 ,quote: `For eternally and always there is only now, one and the same now; the present is the only thing that has no end.`},
    { id:81 ,quote: `Everybody is ‘you’. Everybody is ‘I’. That’s our name. We all share that.`},
    { id:82 ,quote: `The future is a concept, it doesn’t exist. There is no such thing as tomorrow. There never will be because time is always now. That’s one of the things we discover when we stop talking to ourselves and stop thinking. We find there is only present, only an eternal now.`},
    { id:83 ,quote: `Nirvana is right where you are, provided that you don’t object to it.`},
    { id:84 ,quote: `The best way to convince someone is by making him realize that what you speak came from his own mind.`},
    { id:85 ,quote: `Life is not a problem to be solved, but an experience to be had.`},
    { id:86 ,quote: `We have frustration because we are fighting the changing of things.`},
    { id:87 ,quote: `To be implies not to be.`},
    { id:88 ,quote: `Buddha is the man who woke up, who discovered who he really was.`},
    { id:89 ,quote: `This whole world is a phantasmagoria, an amazing illusion.`},
    { id:90 ,quote: `There is nothing except the eternal now.`},
    { id:91 ,quote: `Most problems that are solved in a rush are solved in the wrong way, especially emotional problems between people.`},
    { id:92 ,quote: `The world is precisely the relationship between the world and its witnesses, and so if there are no eyes in this world, the sun doesn’t make any light, nor do the stars.`},
    { id:93 ,quote: `Memory creates the future as well as the past, you wouldn’t know that you were going to have anything happen tomorrow if you didn’t have something yesterday.`},
    { id:94 ,quote: `Choice is not a form of freedom in the sense of the word; choice is the act of hesitation that occurs before making a decision.`},
    { id:95 ,quote: `Every manifestation of life is impermanent. Our quest to make things permanent, to straighten everything out, to get it fixed is an impossible and insoluble problem.`},
    { id:96 ,quote: `Creative people can stimulate creativity in others, by osmosis.`},
    { id:97 ,quote: `Our image of ourselves is completely inaccurate and incomplete.`},
    { id:98 ,quote: `No amount of anxiety makes any difference to anything that is going to happen.`},
    { id:99 ,quote: `The word ‘person’ comes from the latin word ‘persona’ which referred to the masks worn by actors in which sound would come through. The ‘person’ is the mask — the role you’re playing. And all of your friends and relations and teachers are busy telling you who you are and what your role in life is.`},
    { id:100 ,quote: `Education, in the real sense, is not preparation for life, it is actually living. It is the child participating in adult concerns. And doing it now and realizing that the point of the process in which the child is engages, is not to prepare the child for the future, but to enjoy doing the thing today.`},
    { id:101 ,quote: `Faith is, above all, open-ness — an act of trust in the unknown.`}

]

